/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author EstebanDC
 */
public class Empleados extends javax.swing.JFrame {

    int contadorCliente = 0;
    int longitud = 10;
    String nomArchivo = "";

    /**
     * Creates new form Registrar
     */
    public Empleados() {
        initComponents();
        CargarTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImputNombreEmpleado = new javax.swing.JTextField();
        ImputCorreoEmpleado = new javax.swing.JTextField();
        ImputTelefonoEmpleado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardarEmpleado = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        btnEliminaEmpelado = new javax.swing.JButton();
        btnEditarEmpleado = new javax.swing.JButton();
        imputBuscarEmpleado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setLocation(new java.awt.Point(300, 80));
        setName("JframeEmpleado"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImputNombreEmpleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ImputNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImputNombreEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(ImputNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 150, 40));

        ImputCorreoEmpleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ImputCorreoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImputCorreoEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(ImputCorreoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 150, 40));

        ImputTelefonoEmpleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ImputTelefonoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImputTelefonoEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(ImputTelefonoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 150, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 180, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 180, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 180, 70));

        btnGuardarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/save_32.png"))); // NOI18N
        btnGuardarEmpleado.setText("Guardar");
        btnGuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 150, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 180, 70));

        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 570, 170));

        btnEliminaEmpelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/delete.png"))); // NOI18N
        btnEliminaEmpelado.setText("Eliminar");
        btnEliminaEmpelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaEmpeladoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminaEmpelado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 150, 50));

        btnEditarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/icons8-edit-48.png"))); // NOI18N
        btnEditarEmpleado.setText("Editar");
        btnEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 150, 50));

        imputBuscarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        imputBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imputBuscarEmpleadoActionPerformed(evt);
            }
        });
        imputBuscarEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                imputBuscarEmpleadoKeyTyped(evt);
            }
        });
        getContentPane().add(imputBuscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 153, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Modulo de Empleados");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/close.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 150, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/fondo 1.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 780, 600));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void GuardarCliente() {

        ClassGuardarEmpleadosClientes empleado = new ClassGuardarEmpleadosClientes("", "", "", "", "", "", "Empleados",
                ImputNombreEmpleado.getText(),
                ImputTelefonoEmpleado.getText(),
                ImputCorreoEmpleado.getText(),
                contadorCliente);
        if ((ImputNombreEmpleado.getText().length() == 0) || (ImputCorreoEmpleado.getText().length() == 0) || (ImputTelefonoEmpleado.getText().length() == 0)) {
            JOptionPane.showMessageDialog(null, "ERROR: EXISTEN CAMPOS VACIDOS", "ALERTA", JOptionPane.WARNING_MESSAGE);
        } else {
            String correo=ImputCorreoEmpleado.getText();
            String telefono=ImputTelefonoEmpleado.getText();
        int arroba = 0;
        boolean punto = false;
        for (int i = 0; i < correo.length(); i++) {
                    if (correo.charAt(i) == '@') {

                        arroba++;

                    }
                    if (correo.charAt(i) == '.') {
                        punto = true;
                    }
                    if (arroba == 1 && punto == true) {
                        System.out.println("Bingo ");
                    }
                    
                }
        try{
            
           
        if (correo.length() > 6&&arroba == 1 && punto == true) {
                if (telefono.matches("[0-9]+") && telefono.length() == 8) {
                    ImputNombreEmpleado.setText("");
            ImputCorreoEmpleado.setText("");
            ImputTelefonoEmpleado.setText("");
            empleado.CargarEmpleados(jtClientes);
            CargarTable();
              }else{
                 throw new CorreoExcepcion("ERROR: FORMATO DE TELEFONO INVALIDO "); 
              }
              //sdfdfd 
              
            }else{
            throw new CorreoExcepcion("ERROR: FORMATO DE CORREO INVALIDO ");
        }
        }catch (Exception ex) {
                        JOptionPane.showMessageDialog(null,ex.getMessage());

        }
            
        }

        if (contadorCliente < 10) {
            longitud = contadorCliente;
        }
        contadorCliente++;
        // OcultaObjetos();
    }

    public void CargarTable() {
        contadorCliente = 0;
        int num = 0;
        String barra = File.separator;
        String ubicacion = System.getProperty("user.dir") + barra + "Empleados" + barra;
        File archivo = new File(ubicacion);
        FileReader leerArchivo = null;
        File[] registro = archivo.listFiles();
        String[] encabezado = {"ID", "NOMBRE", "CORREO", "TELEFONO"};
        DefaultTableModel model = new DefaultTableModel(null, encabezado);
        for (int i = 0; i < registro.length; i++) {
            File url = new File(ubicacion + registro[i].getName());

            try {
                FileInputStream fis = new FileInputStream(url);
                Properties mostrar = new Properties();
                mostrar.load(fis);

                String filas[] = {registro[i].getName().replace(".txt", ""),
                    mostrar.getProperty("nombre"), mostrar.getProperty("correo"),
                    mostrar.getProperty("telefono")};
                model.addRow(filas);
                num = Integer.parseInt(registro[i].getName().replace(".txt", ""));
                fis.close();

                if (num > contadorCliente) {

                    contadorCliente = num;
                }
            } catch (Exception e) {

            }

        }
        contadorCliente = contadorCliente + 1;
        jtClientes.setModel(model);
        jtClientes.removeColumn(jtClientes.getColumnModel().getColumn(0));

    }

    public void Eliminar(String nomArchivo) {

        String barra = File.separator;
        String ubicacion = System.getProperty("user.dir") + barra + "Empleados" + barra;
        File archivo2 = new File(ubicacion + nomArchivo + ".txt");
        System.out.println(archivo2);
        if (archivo2.delete()) {
            JOptionPane.showMessageDialog(null, "El archivo se borro correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "El archivo no se a eliminado");
        }
        CargarTable();
        //LimpiarEntradas();

    }

    private void ImputCorreoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImputCorreoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImputCorreoEmpleadoActionPerformed

    private void ImputTelefonoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImputTelefonoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImputTelefonoEmpleadoActionPerformed

    private void ImputNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImputNombreEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImputNombreEmpleadoActionPerformed

    private void btnGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpleadoActionPerformed
        // TODO add your handling code here:
        GuardarCliente();
    }//GEN-LAST:event_btnGuardarEmpleadoActionPerformed

    private void btnEliminaEmpeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaEmpeladoActionPerformed
        // TODO add your handling code here:
        int codigo = JOptionPane.showConfirmDialog(null, "Deseas eliminar el Empleado: " + ImputNombreEmpleado.getText(), "Atencion", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (codigo == JOptionPane.YES_OPTION) {
            Eliminar(nomArchivo);
            //btnEliminarUsuario.setVisible(false);
        }
    }//GEN-LAST:event_btnEliminaEmpeladoActionPerformed

    private void jtClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClientesMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) jtClientes.getModel();
        nomArchivo = (String) model1.getValueAt(jtClientes.getSelectedRow(), 0);
        ImputNombreEmpleado.setText((String) model1.getValueAt(jtClientes.getSelectedRow(), 1));
        ImputCorreoEmpleado.setText((String) model1.getValueAt(jtClientes.getSelectedRow(), 2));
        ImputTelefonoEmpleado.setText((String) model1.getValueAt(jtClientes.getSelectedRow(), 3));


    }//GEN-LAST:event_jtClientesMouseClicked

    private void btnEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEmpleadoActionPerformed
        // TODO add your handling code here:
        contadorCliente = Integer.parseInt(nomArchivo);
        GuardarCliente();
    }//GEN-LAST:event_btnEditarEmpleadoActionPerformed
    TableRowSorter trs;
    private void imputBuscarEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imputBuscarEmpleadoKeyTyped
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jtClientes.getModel();
        imputBuscarEmpleado.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                super.keyReleased(ke); //To change body of generated methods, choose Tools | Templates.
                trs.setRowFilter(RowFilter.regexFilter(imputBuscarEmpleado.getText(), 0));
            }

        });
        trs = new TableRowSorter(model);
        jtClientes.setRowSorter(trs);
    }//GEN-LAST:event_imputBuscarEmpleadoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void imputBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imputBuscarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imputBuscarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ImputCorreoEmpleado;
    private javax.swing.JTextField ImputNombreEmpleado;
    private javax.swing.JTextField ImputTelefonoEmpleado;
    private javax.swing.JButton btnEditarEmpleado;
    private javax.swing.JButton btnEliminaEmpelado;
    private javax.swing.JButton btnGuardarEmpleado;
    private javax.swing.JTextField imputBuscarEmpleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtClientes;
    // End of variables declaration//GEN-END:variables
}
